spring:
  cloud:
    gateway:
      routes:
        - id: auth_host_route
          uri: lb://whales-auth
          predicates:
            - Host=auth.whalesocial.com

        - id: user_host_route
          uri: lb://whales-user
          predicates:
            - Host=user.whalesocial.com